Shaked
ElayGelbart/Team-Mongo pull request #2
Opened 2021-11-07 20:34 UTC by shakederin

DAY 1 mission A

2021-11-07 20:47 UTC, ElayGelbart requested changes
Fix

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +const data = require("./database")
Put all your imports together

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +    res.send(data.data);
Bad Name

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +    res.send({Contacts: data.data.length, date:new Date()})
Not right Format

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +    for (let i =0; i<data.data.length; i++){
Could use for(value of array)

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +        if(+data.data[i].id === +id){
Not use `Math.random()`

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +    res.sendStatus(404);
what about special msg

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +            console.log(data.data);
console log in publish code

2021-11-07 20:47 UTC, ElayGelbart commented on src/server.js
> +            idNumber = data.data[i].id
?????

2021-11-10 10:18 UTC, ElayGelbart reviewed
enjoy

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.html
> +    <nav id="navBar">
why id ?

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.html
> +    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
axios in head

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.js
> +    const fullName = firstName + " " + lastName;
`${}`

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.js
> +    favorite.addEventListener("click", function(){makeFavorite(contact)});
why Favourite

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.js
> +async function deleteContact(contact, name){
what is contact? element? string? number?

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.js
> +    const data = await axios.get(`${myAPI}/api/persons`);
slow, why get and also delete

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/index.js
> +        if(data.data[i].name === name){
data data

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/style.css
> +    margin-bottom: 5%;
why %

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/style.css
> +    left: 47%;
%?

2021-11-10 10:18 UTC, ElayGelbart commented on frontend/style.css
> +    left: 47%;
`display:flex`

2021-11-10 10:18 UTC, ElayGelbart commented on toDataBase/mongo.js
> +require('dotenv').config();
if you use argv you dont need dotenv

2021-11-10 10:18 UTC, ElayGelbart commented on webpack.config.js
> +//   devtool: 'eval-source-map',
delete `//`

2021-11-11 09:59 UTC, EhoodGoren requested changes

2021-11-11 09:59 UTC, EhoodGoren commented on .env
> +DATABASE = "mongodb+srv://shakederin:shaked12345675@cluster0.7gngs.mongodb.net/phonebook?retryWrites=true&w=majority"
Dont commit .env file

2021-11-11 09:59 UTC, EhoodGoren commented on models/note.js
> +    name: String,
require?

2021-11-11 09:59 UTC, EhoodGoren commented on models/note.js
> +mongoose.connect(connectionString)
Don't connect in model

2021-11-11 09:59 UTC, EhoodGoren commented on models/note.js
> +const phoneBookSchema = new mongoose.Schema({
separate model

2021-11-11 09:59 UTC, EhoodGoren commented on models/note.js
> +function program(password, name, phoneNum){
this doesn't belong here

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +const Note = require('../models/note');
Note?

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +const connectionString = process.env.DATABASE;
Not used

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +        res.status(400).send("Cant find person");
Use error handler

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +    if (req.body === undefined) {
!req.body

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +        return res.status(400).json({ error: 'content missing' })
Use the same format for errors

2021-11-11 09:59 UTC, EhoodGoren commented on src/server.js
> +        res.send(error);
Another error format

2023-11-26 09:21 UTC, closed without merging